### ISSUE TITLE
Inferencing script

### ISSUE THREAD

**Issue by ghost** [descriptinc/melgan-neurips#1] opened 2019-10-28 05:32 UTC
@ritheshkumar95 
- Once we finished training,  how to use the trained model to generate audio.
- Further documentation on  inferencing.

**Comment by candlewill** [comment] 2019-10-29 03:32
Same problem here.

**Comment by candlewill** [comment] 2019-11-11 11:28
The generated wave was very strange:


![image](https://user-images.githubusercontent.com/4916563/68583877-36054f80-04b9-11ea-8915-354ddbdc27e9.png)

**Comment by ghost** [comment] 2019-11-17 17:03
@ritheshkumar95

**Comment by candlewill** [comment] 2019-11-19 07:18
Here is the code to do copy-synth:

```python
>>> from mel2wav import MelVocoder
>>> import librosa
>>> wav = librosa.load("110001-121906/110010.wav", 22050)[0]
>>> import torch
>>> wav = torch.from_numpy(wav)

>>> vocoder = MelVocoder("logs/baseline/")
>>> mel = vocoder(wav)
>>> wav = wav.unsqueeze(0)
>>> mel = vocoder(wav)
>>> mel.shape
torch.Size([1, 80, 503])
>>> rev_wav = vocoder.inverse(mel)
>>> rev_wav.shape
torch.Size([1, 128768])
>>> rev_wav.dtype
torch.float32
>>> rev_wav = rev_wav.cpu().numpy()
>>> rev_wav.shape
(1, 128768)
>>> rev_wav
array([[-9.3722469e-05,  2.6575495e-05,  4.6295419e-05, ...,
        -3.0277806e-04,  2.2566912e-05, -1.2692061e-04]], dtype=float32)
>>> from scipy.io import wavfile

>>> import numpy as np



wavfile.write("res.wav", 22050, (rev_wav.reshape((-1))*2**15).astype(np.int16))
```

**Comment by Teravus** [comment] 2020-03-05 04:24
There's already an inferencing script in the scripts folder, 'generate_from_folder.py' 
Drop it into the parent folder.

Make a folder, fill your folder with wav files with spoken text that you want to apply your trained model to.

Example call to the inference script
python generate_from_folder.py --load_path logs/baseline --save_path logs --folder t

**Comment by Teravus** [comment] 2020-03-05 04:32
One more thing on that inferencing script.  If you get an unable to unpack error, on line 29, remove the comma and underscore.   the vocoder call seems to return one result instead of 2 now.
mel, _ = vocoder(torch.from_numpy(wav)[None]) 
to 
mel = vocoder(torch.from_numpy(wav)[None])

**Comment by ghost** [comment] 2020-03-06 11:56
@Teravus share your generated results here, so i hear if it's good or bad.

**Comment by Teravus** [comment] 2020-03-07 18:08
This technique requires a lot of (millions of) iterations.   I'm only at iteration 75000.   I input my own voice and the output sounds sounds exactly like the test generations of a different voice (custom dataset) which are not that great yet.

**Comment by ghost** [comment] 2020-03-07 18:56
@Teravus once you achieve good results, post them here

**Comment by Teravus** [comment] 2020-04-19 04:34
I trained the generator model for about 800,000 steps and it essentially stopped getting better.  The loss figures became a straight line over the time axis.  With the generated samples,  The lower portions of the audio sound great but also have a waver in the audio.  The higher points of the audio where more emphasis was spoken by the speaker were essentially chopped out of the result.   The low portions of the generates samples sound pretty good with the samples generated, however...  when attempted to apply the features to a different speaker, it just wasn't good enough.  I can hear the new speaker clearly over the features applied of the trained speaker.

What I eventually did that, still sounded a bit digital.. but was massively better  was generate audio with CorentinJ / Real-Time-Voice-Cloning using the same samples that I trained melgan-neurips on and *then* transferring the trained speaker features to the output of RTVC using Melgan-neurips


[melgan-output-sample.zip](https://github.com/descriptinc/melgan-neurips/files/4498373/melgan-output-sample.zip)

**Comment by ghost** [comment] 2020-04-19 18:08
@Teravus 
The sample that you uploaded is not good.
- what loss / accuracy did you achieve
- generate an audio sample using groundtruth, and upload here so i can hear what accuracy it can achieve

**Comment by Teravus** [comment] 2020-04-19 18:37
I have processed it as much as I am going to.   If you would like to know the quality you will achieve, you can spend the computing resources and do so yourself.  
I found it to be slightly better when the melgan-neurips features are applied over top of a wav generated with the Griffin-Lim vocoder.   Still nothing like the descriptinc sample video though.

**Comment by Teravus** [comment] 2020-04-19 18:42
Loss values:
generator: 11.79
feature_matching: 1.101
mel_reconstruction: 0.3811
discriminator: 1.408

**Comment by Mariaa98** [comment] 2020-05-08 20:42
@Teravus  I did this command that you mentioned above after training `python generate_from_folder.py --load_path logs/baseline --save_path logs --folder t`
and give me this error 
Error : ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:pathlib.PosixPath'
  in "logs/baseline/args.yml", line 4, column 12

any one can help
Thank u

**Comment by Teravus** [comment] 2020-05-09 03:22
Seems like it wasn't able to read your model from the --load_path parameter.    Is your model in a subfolder called logs and a subfolder of that called baseline?

**Comment by joshgreifer** [comment] 2020-06-03 10:28
For the args.yml issue,  this in my case was caused by a spurious line `data_path: !!python/object/apply:pathlib.PosixPath []` which was introduced by passing an invalid data_path on an invocation of the training script.   Just remove it from the yaml file.

**Comment by materialvision** [comment] 2020-08-14 05:13
@Mariaa98 I fixed the args.yml issue by installing an earlier version of yml, pip install pyyaml==5.1

**Closed as completed** 2020-08-16 14:30 UTC
